--liquibase formatted sql
--changeSet dev_0001:001-01

CREATE TABLE clients
(
    client_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name            VARCHAR(20)  NOT NULL,
    address              VARCHAR(100) NOT NULL,
    payer_account_number VARCHAR(40)  NOT NULL UNIQUE,
    bank_details         VARCHAR(100) NOT NULL
);

-- rollback DROP TABLE clients;