--liquibase formatted sql
--changeSet dev_0001:001-01

CREATE TABLE products
(
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL UNIQUE,
    price        DECIMAL      NOT NULL,
    quantity     INTEGER      NOT NULL,
    unit         VARCHAR(10)  NOT NULL
);

-- rollback DROP TABLE products;