apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service-deployment
  labels:
    app: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: crm-base-db-service
          image: crm-base-db-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-configuration
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configuration
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-credentials


